- hosts: ec2
  become: yes
  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar pacotes básicos do sistema
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Instalar bibliotecas Python (boto3, pandas)
      pip:
        name:
          - boto3
          - pandas
        executable: pip3
        extra_args: --break-system-packages

    - name: Criar diretórios de dados
      file:
        path: "/data/{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - raw
        - trusted
        - client

